---
- name: helloworld
  hosts: local
  connection: local
  tasks:
  - name: hello playbook
    ansible.builtin.debug:
      msg: "hello playbook"
    registry: result

  - name: print result
    ansible.builtin.debug:
      msg: "{{result}}"