---
- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: command ls command 
    ansible.builtin.command: ls -ltr > /tmp/output.txt
  - name: shell ls command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
