---
- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: command ls command 
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    ignore_errors: true

  - name: shell ls command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: ls command
    ansible.builtin.command: lsffff -ltr
    register: command_result
    
  - name: print output
    ansible.builtin.debug:
      msg: "{{command_result}}"
