---
- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: command ls command 
    ansible.builtin.command: ls -ltr > /tmp/output.txt
    ignore_errors: true

  - name: shell ls command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: ls command
    ansible.builtin.command: lsffff -ltr
    register: command_result
    ignore_errors: true

  - name: print output
    ansible.builtin.debug:
      msg: "{{code: command_result.rc}}"
  
  - name: Run a command
    ansible.builtin.command: /bin/echo "Hello, World!"
    register: result

  - name: Display the return code
    ansible.builtin.debug:
      msg: "Return code: {{ result.rc }}"

