---
- name: create ec2 instance 
  hosts: local
  connection: local
  vars:
    instance_type: t2.micro
    security_group: sg-06664a65d9522acf5 
    image_id: ami-09c813fb71547fc4f
    subnet_id: subnet-00d643a230b615c78
    vpc_id: vpc-0f4319f8fc9fa30af
    zone: kommanuthala.store
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: python libs
    ansible.builtin.pip:
      name: " {{ item }}"
    loop: 
    - boto3
    - botocore

  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: " {{subnet_id}}"
      security_group: "{{security_group}}"
      image_id: "{{image_id}}"
      instance_type: "{{instance_type}}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print ec2 instance
    ansible.builtin.debug:
      msg: "test"
      
  - name: print private ip address
    ansible.builtin.debug:
      msg: "{{item.instances[0].network_interfaces[0].private_ip_address}}"
    loop: "{{ec2_info.results}}"

  - name: create private ip address 
    amazon.aws.route53:
      state: present
      zone: "{{item.item}}.{{zone}}"
      type: A
      ttl: 1
      value: "{{item.instances[0].network_interfaces[0].private_ip_address}}"
      overwrite: true
      wait: true
    loop: "{{ec2_info.results}}"
      